### PR TITLE
Make Sprockets support optional

### PR DESCRIPTION
**Pull request by florentmorin**
Rails API has no Sprockets support

### CODE REVIEW

**Comment by romanbsd** [comment]
Does one need to use this gem for a pure Rails-API app?

**Comment by florentmorin** [comment]
GZip for JSON Data.

**Comment by romanbsd** [comment]
It's possible to add the Rack::Deflate to the rack stack in this case. I don't think that you need the extra features that this gem provides.

**Comment by uberllama** [comment]
We just ran into this today, after upgrading from Rails 4.2 to Rails 5. We deploy a Rails API together with a webpack-based React app. With Rails 4.2, we were able to comment out the sprockets require. With Rails 5, we need to require it.

**Comment by uberllama** [comment]
Update: I opted for plain old Rack::Deflater instead for my JSON and will use compression for my CDN-served assets. Cheers.

**Pull request closed without merging**
